#!/bin/bash

#./apache-activemq-5.10.0/bin/activemq start &
java -jar Sensor.jar -r 10 -udpPort 9998 &
java -jar HouseServer.jar -sp 8080 -ep 8081 -udpPort 9998 -tcpPort 9999 &
java -jar Sensor.jar -r 10 -udpPort 9997 &
java -jar HouseServer.jar -sp 8081 -ep 8082 -udpPort 9997 -tcpPort 9996 &
java -jar AdminServer.jar -sp 8080 -ep 8082 -t 5000 -ip localhost -n 1 -mqIp localhost -mqPort 61616 -o status